name: 'localhost-test'
s3:
  endpoint: 'http://localhost:9000'
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_ACCESS_SECRET}
celery:
  broker: 'redis://localhost:6379'
  backend: 'redis://localhost:6379'