name: 'localhost-test'
storage:
  s3:
    endpoint: 'http://aws-s3:9000'
    access_key_id: minio
    secret_access_key: minio123
    use_ssl: False
    verify: False
    uploads_bucket: 'temp-uploads'
celery:
  broker: 'redis://redisdb:6379'
  backend: 'redis://redisdb:6379'
dask:
  scheduler: 'tcp://dask-scheduler:8786'
database:
  sql:
    url: !ENV 'mysql+pymysql://${MYSQL_APP_USER}:${MYSQL_APP_PASSWORD}@localhost:3306/cryptoml?charset=utf8mb4'
  influxdb:
    host: 'influxdb'
    port: 8086
    username: !ENV ${INFLUXDB_USERNAME}
    password: !ENV ${INFLUXDB_PASSWORD}
    database: 'db0'
kraken:
  key: ''