version: '3.7'

services:
  cryptoml-api:
    image: mrlicorice/cryptoml-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: cryptoml-api
    ports:
      - "8000:8000"
    configs:
      - source: cryptoml_config
        target: /app/config.yml
    secrets:
      - source: cryptoml_env
        target: /app/.env
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1

  dask-scheduler:
    image: mrlicorice/cryptoml-api:latest
    hostname: dask-scheduler
    entrypoint: dask-scheduler
    configs:
      - source: cryptoml_config
        target: /app/config.yml
    secrets:
      - source: cryptoml_env
        target: /app/.env
    ports:
      - "8786:8786"
      - "8787:8787"
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DASK_DISTRIBUTED__SCHEDULER__WORK_STEALING=True
      - DASK_DISTRIBUTED__SCHEDULER__ALLOWED_FAILURES=5

  celery-worker-default:
    image: mrlicorice/cryptoml-api:latest
    entrypoint: celery -A worker.celery worker --loglevel=info --concurrency 4
    configs:
      - source: cryptoml_config
        target: /app/config.yml
    secrets:
      - source: cryptoml_env
        target: /app/.env
    networks:
      - internal
    deploy:
      endpoint_mode: dnsrr # Use DNSRR because each service container must have its own IP address and not a Virtual IP!
      mode: replicated
      replicas: 1

  celery-worker-system:
    image: mrlicorice/cryptoml-api:latest
    entrypoint: celery -A worker.celery worker --loglevel=info -Q system --concurrency 2
    configs:
      - source: cryptoml_config
        target: /app/config.yml
    secrets:
      - source: cryptoml_env
        target: /app/.env
    networks:
      - internal
    deploy:
      endpoint_mode: dnsrr # Use DNSRR because each service container must have its own IP address and not a Virtual IP!
      mode: replicated
      replicas: 1

  dask-worker:
    image: mrlicorice/cryptoml-api:latest
    configs:
      - source: cryptoml_config
        target: /app/config.yml
    secrets:
      - source: cryptoml_env
        target: /app/.env
    depends_on:
      - dask-scheduler
    entrypoint: dask-worker --no-dashboard --no-nanny --interface eth0 --nprocs 1 --nthreads 4 --lifetime 900s tcp://dask-scheduler:8786
    networks:
      - internal
    deploy:
      endpoint_mode: dnsrr # Use DNSRR because each service container must have its own IP address and not a Virtual IP!
      mode: replicated
      replicas: 4

  redis:
    image: 'redis:6-alpine'
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    configs:
      - source: redis_config
        target: /redis.conf
    volumes:
      - 'redis-data-1:/data'
    networks:
      - internal

networks:
  internal:
    driver: overlay
    attachable: true

volumes:
  redis-data-1:

configs:
  cryptoml_config:
    file: ./config-docker.yml
  redis_config:
    file: ./docker/redis/redis.conf

secrets:
  cryptoml_env:
    file: ./.env
    
