FROM ubuntu:20.04

RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev redis-tools

# We copy just the requirements.txt first to leverage Docker cache
COPY ./src/requirements.txt /src/requirements.txt

WORKDIR /src

RUN pip3 install -r requirements.txt

COPY ./src /src

WORKDIR /
COPY ./worker.py /worker.py
# Use a different config file for docker environment
COPY ./.env /.env
COPY ./config-docker.yml /config.yml

RUN useradd -ms /bin/bash worker
RUN chown -R worker:worker /src
RUN chown worker:worker /worker.py
RUN chown worker:worker /config.yml
RUN chown worker:worker /.env

USER worker

ENTRYPOINT [ "python3" ]
CMD [ "worker.py" ]
ENTRYPOINT celery -A worker.celery worker --loglevel=info