version: '3.7'

services:
  cryptoml-api:
    image: redlicorice/cryptoml-api
    container_name: cryptoml-api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: cryptoml-api
    ports:
      - "8000:8000"
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './app:/app'
    networks:
      - cryptoml-network
      - mongodb-network
      - minio-network
      - redis-network
      - influxdb-network

networks:
  cryptoml-network:

  minio-network:
  mongodb-network:
  redis-network:
  influxdb-network:
