version: '3.7'

services:
  ml-service:
    image: redlicorice/cryptoml-api
    build:
      context: .
      dockerfile: API.dockerfile
    hostname: mlservice
    ports:
      - "8000:5000"
    networks:
      - cryptoml-network
      - mongodb-network
      - minio-network
      - redis-network
      - influxdb-network

  ml-worker1:
    image: redlicorice/cryptoml-api-worker
    build:
      context: .
      dockerfile: Worker.dockerfile
    hostname: mlservice
    volumes:
      - './.env:/.env'
      - './config-docker.yml:/config.yml'
    networks:
      - cryptoml-network
      - mongodb-network
      - minio-network
      - redis-network
      - influxdb-network

networks:
  cryptoml-network:

  minio-network:
    external: true
  mongodb-network:
    external: true
  redis-network:
    external: true
  influxdb-network:
    external: true
