version: '3.7'

services:
  cryptoml-api:
    image: redlicorice/cryptoml-api
    container_name: cryptoml-api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: cryptoml-api
    ports:
      - "8000:8000"
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './app:/app'
    networks:
      - cryptoml-network

  dask-scheduler:
    image: mrlicorice/cryptoml-api:latest
    container_name: dask-scheduler
    hostname: dask-scheduler
    entrypoint: ["dask-scheduler"]
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './app:/app'
    ports:
      - "8786:8786"
      - "8787:8787"
    networks:
      - cryptoml-network

  dask-worker-1:
    image: mrlicorice/cryptoml-api:latest
    container_name: dask-worker-1
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './app:/app'
    depends_on:
      - dask-scheduler
    entrypoint: ["dask-worker", "tcp://dask-scheduler:8786"]
    networks:
      - cryptoml-network

  dask-worker-2:
    image: mrlicorice/cryptoml-api:latest
    container_name: dask-worker-2
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './app:/app'
    depends_on:
      - dask-scheduler
    entrypoint: [ "dask-worker", "tcp://dask-scheduler:8786" ]
    networks:
      - cryptoml-network

  celery-worker-1:
    image: mrlicorice/cryptoml-api:latest
    container_name: celery-worker-1
    entrypoint: celery -A worker.celery worker --loglevel=info
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './app:/app'
    networks:
      - cryptoml-network

networks:
  cryptoml-network:
