version: '3.7'

services:
  celery-worker-1:
    image: mrlicorice/cryptoml-api:latest
    container_name: celery-worker-1
    entrypoint: celery -A worker.celery worker --loglevel=info
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './app:/app'
    networks:
      - cryptoml-network

networks:
  cryptoml-network:
    external: true