version: '3.7'

services:
  celery-worker1:
    image: redlicorice/cryptoml-celery-worker
    build:
      context: .
      dockerfile: Worker.dockerfile
    hostname: mlservice
    volumes:
      - './.env:/.env'
      - './config-docker.yml:/config.yml'
      - './cryptoml:/cryptoml'
      - './cryptoml_api:/cryptoml_api'
    networks:
      - cryptoml-network
      - mysql-network
      - minio-network
      - redis-network
      - dask-network
      - influxdb-network

networks:
  cryptoml-network:
  minio-network:
    external: true
  mysql-network:
    external: true
  redis-network:
    external: true
  dask-network:
    external: true
  influxdb-network:
    external: true