version: '3.7'

services:
  dask-scheduler:
    image: redlicorice/cryptoml-api
    container_name: dask-scheduler
#    build:
#      context: .
#      dockerfile: Dockerfile
    hostname: dask-scheduler
    entrypoint: ["dask-scheduler"]
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './cryptoml:/app/cryptoml'
      - './cryptoml_api:/app/cryptoml_api'
      - './cryptoml_core:/app/cryptoml_core'
    ports:
      - "8786:8786"
      - "8787:8787"
    networks:
      - cryptoml-network
      - mongodb-network
      - minio-network
      - redis-network
      - influxdb-network

  dask-worker-1:
    image: redlicorice/cryptoml-api
    container_name: dask-worker-1
#    build:
#      context: .
#      dockerfile: Dockerfile
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './cryptoml:/app/cryptoml'
      - './cryptoml_api:/app/cryptoml_api'
      - './cryptoml_core:/app/cryptoml_core'
    depends_on:
      - dask-scheduler
    entrypoint: ["dask-worker", "tcp://dask-scheduler:8786"]
    networks:
      - cryptoml-network
      - mongodb-network
      - minio-network
      - redis-network
      - influxdb-network

  dask-worker-2:
    image: redlicorice/cryptoml-api
    container_name: dask-worker-2
#    build:
#      context: .
#      dockerfile: Dockerfile
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './cryptoml:/app/cryptoml'
      - './cryptoml_api:/app/cryptoml_api'
      - './cryptoml_core:/app/cryptoml_core'
    depends_on:
      - dask-scheduler
    entrypoint: [ "dask-worker", "tcp://dask-scheduler:8786" ]
    networks:
      - cryptoml-network
      - mongodb-network
      - minio-network
      - redis-network
      - influxdb-network

networks:
  cryptoml-network:
    external: true
  minio-network:
    external: true
  mongodb-network:
    external: true
  redis-network:
    external: true
  influxdb-network:
    external: true