version: '3.7'

services:
  celery-worker-1:
    image: redlicorice/cryptoml-worker
    container_name: celery-worker-1
    build:
      context: .
      dockerfile: docker/Worker.dockerfile
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './cryptoml:/app/cryptoml'
      - './cryptoml_api:/app/cryptoml_api'
      - './cryptoml_core:/app/cryptoml_core'
    networks:
      - cryptoml-network
      - mongodb-network
      - minio-network
      - redis-network
      - influxdb-network

networks:
  cryptoml-network:
    external: true
  minio-network:
    external: true
  mongodb-network:
    external: true
  redis-network:
    external: true
  influxdb-network:
    external: true