version: '3.7'

services:
  cryptoml-api:
    image: mrlicorice/cryptoml-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: cryptoml-api
    ports:
      - "8000:8000"
    configs:
      - source: cryptoml_config
        target: /app/config.yml
    secrets:
      - source: cryptoml_env
        target: /app/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1

  dask-scheduler:
    image: mrlicorice/cryptoml-api:latest
    hostname: dask-scheduler
    entrypoint: dask-scheduler
    configs:
      - source: cryptoml_config
        target: /app/config.yml
    secrets:
      - source: cryptoml_env
        target: /app/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8786:8786"
      - "8787:8787"
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1

  celery-worker:
    image: mrlicorice/cryptoml-api:latest
    entrypoint: celery -A worker.celery worker --loglevel=info
    configs:
      - source: cryptoml_config
        target: /app/config.yml
    secrets:
      - source: cryptoml_env
        target: /app/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1

  dask-worker:
    image: mrlicorice/cryptoml-api:latest
    configs:
      - source: cryptoml_config
        target: /app/config.yml
    secrets:
      - source: cryptoml_env
        target: /app/.env
    depends_on:
      - dask-scheduler
    entrypoint: dask-worker tcp://dask-scheduler:8786
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 6
      resources:
        limits:
          cpus: '0.50'
          memory: 2Gi
        reservations:
          cpus: '0.25'
          memory: 500M

  redis:
    image: 'redis:6-alpine'
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    configs:
      - source: redis_config
        target: /redis.conf
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - 'redis-data-1:/data'
    networks:
      - internal

networks:
  internal:
    driver: overlay
    attachable: true

volumes:
  redis-data-1:

configs:
  cryptoml_config:
    file: ./config-docker.yml
  redis_config:
    file: ./docker/redis/redis.conf

secrets:
  cryptoml_env:
    file: ./.env
    
