version: '3.7'

services:
  dask-scheduler:
    image: redlicorice/cryptoml-worker
    container_name: dask-scheduler
    build:
      context: .
      dockerfile: docker/Worker.dockerfile
    hostname: dask-scheduler
    entrypoint: ["dask-scheduler"]
#    volumes:
#      - './cryptoml:/python-dependencies/cryptoml'
#      - './cryptoml_common:/python-dependencies/cryptoml_common'
    ports:
      - "8786:8786"
      - "8787:8787"
    networks:
      dask-network:
        aliases:
          - daskscheduler
          - dask-scheduler

  dask-worker-1:
    image: redlicorice/cryptoml-worker
    container_name: dask-worker-1
    build:
      context: .
      dockerfile: docker/Worker.dockerfile
#    volumes:
#      - './cryptoml:/python-dependencies/cryptoml'
#      - './cryptoml_common:/python-dependencies/cryptoml_common'
    depends_on:
      - dask-scheduler
    entrypoint: ["dask-worker", "tcp://dask-scheduler:8786"]
    networks:
      dask-network:

  dask-worker-2:
    image: redlicorice/cryptoml-worker
    container_name: dask-worker-2
    build:
      context: .
      dockerfile: docker/Worker.dockerfile
#    volumes:
#      - './cryptoml:/python-dependencies/cryptoml'
#      - './cryptoml_common:/python-dependencies/cryptoml_common'
    depends_on:
      - dask-scheduler
    entrypoint: [ "dask-worker", "tcp://dask-scheduler:8786" ]
    networks:
      dask-network:

networks:
  dask-network: