version: '3.7'

services:
  ml-service:
    image: redlicorice/cryptoml-api
    build:
      context: .
      dockerfile: docker/API.dockerfile
    hostname: mlservice
    ports:
      - "8000:8000"
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './cryptoml:/app/cryptoml'
      - './cryptoml_api:/app/cryptoml_api'
      - './cryptoml_core:/app/cryptoml_core'
    networks:
      - cryptoml-network
      - mongodb-network
      - minio-network
      - redis-network
      - influxdb-network
      - dask-network

  ml-worker1:
    image: redlicorice/cryptoml-api-worker
    build:
      context: .
      dockerfile: docker/Worker.dockerfile
    hostname: mlservice
    volumes:
      - './.env:/app/.env'
      - './config-docker.yml:/app/config.yml'
      - './cryptoml:/app/cryptoml'
      - './cryptoml_api:/app/cryptoml_api'
      - './cryptoml_core:/app/cryptoml_core'
    networks:
      - cryptoml-network
      - mongodb-network
      - minio-network
      - redis-network
      - influxdb-network
      - dask-network

networks:
  cryptoml-network:
  minio-network:
    external: true
  mongodb-network:
    external: true
  redis-network:
    external: true
  influxdb-network:
    external: true
  dask-network:
    external: true
