version: '3.7'

services:
  redis:
    image: 'redis:alpine'
    container_name: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - 'redis-data-1:/data'
    expose:
      - '6379'
    ports:
      - '6379:6379'
    networks:
      - redis-network

volumes:
  redis-data-1:

networks:
  redis-network: