version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - './docker/mongodb:/data/configdb'
      - 'mongodb-data-1:/var/lib/mongo'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    expose:
      - '27017'
    ports:
      - '27017:27017'
    networks:
      mongodb-network:
        aliases:
          - mongodb

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=27017
    expose:
      - '8081'
    ports:
      - '8081:8081'
    networks:
      mongodb-network:

volumes:
  mongodb-data-1:

networks:
  mongodb-network:
    external: true