@echo off
python manage_dataset.py build ADAUSD merged ohlcv coinmetrics
python manage_dataset.py build BCHUSD merged ohlcv coinmetrics
python manage_dataset.py build BNBUSD merged ohlcv coinmetrics
python manage_dataset.py build BTCUSD merged ohlcv coinmetrics
python manage_dataset.py build BTGUSD merged ohlcv coinmetrics
python manage_dataset.py build DASHUSD merged ohlcv coinmetrics
python manage_dataset.py build DOGEUSD merged ohlcv coinmetrics
python manage_dataset.py build EOSUSD merged ohlcv coinmetrics
python manage_dataset.py build ETCUSD merged ohlcv coinmetrics
python manage_dataset.py build ETHUSD merged ohlcv coinmetrics
python manage_dataset.py build LINKUSD merged ohlcv coinmetrics
python manage_dataset.py build LTCUSD merged ohlcv coinmetrics
python manage_dataset.py build NEOUSD merged ohlcv coinmetrics
python manage_dataset.py build QTUMUSD merged ohlcv coinmetrics
python manage_dataset.py build TRXUSD merged ohlcv coinmetrics
python manage_dataset.py build USDTUSD merged ohlcv coinmetrics
python manage_dataset.py build VENUSD merged ohlcv coinmetrics
python manage_dataset.py build WAVESUSD merged ohlcv coinmetrics
python manage_dataset.py build XEMUSD merged ohlcv coinmetrics
python manage_dataset.py build XMRUSD merged ohlcv coinmetrics
python manage_dataset.py build XRPUSD merged ohlcv coinmetrics
python manage_dataset.py build ZECUSD merged ohlcv coinmetrics
python manage_dataset.py build ZRXUSD merged ohlcv coinmetrics