name: 'external-services-test'
storage:
  # S3 Minio storage
  s3:
    endpoint: !ENV http://cupcaketest.duckdns.org:${MINIO_PORT}
    access_key_id: !ENV ${AWS_ACCESS_KEY_ID}
    secret_access_key: !ENV ${AWS_SECRET_ACCESS_KEY}
    use_ssl: False
    verify: False
    uploads_bucket: 'temp-uploads'
    loglevel: 'INFO'
# dask:
#  scheduler: 'tcp://dask-scheduler:8786'
database:
  influxdb:
    host: 'cupcaketest.duckdns.org'
    port: !ENV ${INFLUXDB_PORT}
    username: !ENV ${INFLUXDB_USERNAME}
    password: !ENV ${INFLUXDB_PASSWORD}
    database: 'db0'
    udp: false
    udp_port: 4444
  mongo:
    # If using docker ssl=true&retrywrites=false&ssl_cert_reqs=CERT_NONE
    uri: !ENV mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@cupcaketest.duckdns.org:${MONGODB_PORT}
    database: 'cryptoml'
  redis:
    uri: !ENV redis://redis:${REDIS_PORT}
    password: !ENV ${REDIS_PASSWORD}
kraken:
  key: ''