@echo off
python grid_search_new.py ADAUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py ADAUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ADAUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py ADAUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py ADAUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py ADAUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ADAUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py ADAUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py ADAUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py ADAUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py ADAUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py BCHUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py BCHUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py BCHUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py BCHUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py BCHUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py BCHUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py BCHUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py BCHUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py BCHUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py BCHUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py BCHUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py BNBUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py BNBUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py BNBUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py BNBUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py BNBUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py BNBUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py BNBUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py BNBUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py BNBUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py BNBUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py BNBUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py BTCUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py BTCUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py BTCUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py BTCUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py BTCUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py BTCUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py BTCUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py BTCUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py BTCUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py BTCUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py BTCUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py BTGUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py BTGUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py BTGUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py BTGUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py BTGUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py BTGUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py BTGUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py BTGUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py BTGUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py BTGUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py BTGUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py DASHUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py DASHUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py DASHUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py DASHUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py DASHUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py DASHUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py DASHUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py DASHUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py DASHUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py DASHUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py DASHUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py DOGEUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py DOGEUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py DOGEUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py DOGEUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py DOGEUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py DOGEUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py DOGEUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py DOGEUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py DOGEUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py DOGEUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py DOGEUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py EOSUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py EOSUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py EOSUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py EOSUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py EOSUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py EOSUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py EOSUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py EOSUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py EOSUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py EOSUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py EOSUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ETCUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py ETCUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ETCUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py ETCUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py ETCUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py ETCUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ETCUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py ETCUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py ETCUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py ETCUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py ETCUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ETHUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py ETHUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ETHUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py ETHUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py ETHUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py ETHUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ETHUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py ETHUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py ETHUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py ETHUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py ETHUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py LINKUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py LINKUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py LINKUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py LINKUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py LINKUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py LINKUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py LINKUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py LINKUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py LINKUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py LINKUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py LINKUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py LTCUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py LTCUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py LTCUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py LTCUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py LTCUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py LTCUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py LTCUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py LTCUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py LTCUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py LTCUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py LTCUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py NEOUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py NEOUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py NEOUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py NEOUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py NEOUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py NEOUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py NEOUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py NEOUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py NEOUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py NEOUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py NEOUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py QTUMUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py QTUMUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py QTUMUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py QTUMUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py QTUMUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py QTUMUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py QTUMUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py QTUMUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py QTUMUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py QTUMUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py QTUMUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py TRXUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py TRXUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py TRXUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py TRXUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py TRXUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py TRXUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py TRXUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py TRXUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py TRXUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py TRXUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py TRXUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py VENUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py VENUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py VENUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py VENUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py VENUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py VENUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py VENUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py VENUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py VENUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py VENUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py VENUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py WAVESUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py WAVESUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py WAVESUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py WAVESUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py WAVESUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py WAVESUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py WAVESUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py WAVESUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py WAVESUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py WAVESUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py WAVESUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py XEMUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py XEMUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py XEMUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py XEMUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py XEMUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py XEMUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py XEMUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py XEMUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py XEMUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py XEMUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py XEMUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py XMRUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py XMRUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py XMRUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py XMRUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py XMRUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py XMRUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py XMRUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py XMRUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py XMRUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py XMRUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py XMRUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py XRPUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py XRPUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py XRPUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py XRPUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py XRPUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py XRPUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py XRPUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py XRPUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py XRPUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py XRPUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py XRPUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ZECUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py ZECUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ZECUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py ZECUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py ZECUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py ZECUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ZECUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py ZECUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py ZECUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py ZECUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py ZECUSD merged_new class smote_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ZRXUSD merged_new class bagging_decisiontree --feature-selection-method importances_shap
python grid_search_new.py ZRXUSD merged_new class bagging_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ZRXUSD merged_new class plain_knn --feature-selection-method importances_shap
python grid_search_new.py ZRXUSD merged_new class plain_mlp --feature-selection-method importances_shap
python grid_search_new.py ZRXUSD merged_new class plain_mnb --feature-selection-method importances_shap
python grid_search_new.py ZRXUSD merged_new class plain_poly_svc --feature-selection-method importances_shap
python grid_search_new.py ZRXUSD merged_new class plain_randomforest --feature-selection-method importances_shap
python grid_search_new.py ZRXUSD merged_new class plain_xgboost --feature-selection-method importances_shap
python grid_search_new.py ZRXUSD merged_new class smote_knn --feature-selection-method importances_shap
python grid_search_new.py ZRXUSD merged_new class smote_mlp --feature-selection-method importances_shap
python grid_search_new.py ZRXUSD merged_new class smote_poly_svc --feature-selection-method importances_shap