@echo off
python dataset.py load temp-uploads ohlcv/ada.csv ohlcv ADAUSD
python dataset.py load temp-uploads coinmetrics/ada.csv coinmetrics ADAUSD
python dataset.py load temp-uploads ohlcv/bch.csv ohlcv BCHUSD
python dataset.py load temp-uploads coinmetrics/bch.csv coinmetrics BCHUSD
python dataset.py load temp-uploads ohlcv/bnb.csv ohlcv BNBUSD
python dataset.py load temp-uploads coinmetrics/bnb.csv coinmetrics BNBUSD
python dataset.py load temp-uploads ohlcv/btc.csv ohlcv BTCUSD
python dataset.py load temp-uploads coinmetrics/btc.csv coinmetrics BTCUSD
python dataset.py load temp-uploads ohlcv/btg.csv ohlcv BTGUSD
python dataset.py load temp-uploads coinmetrics/btg.csv coinmetrics BTGUSD
python dataset.py load temp-uploads ohlcv/dash.csv ohlcv DASHUSD
python dataset.py load temp-uploads coinmetrics/dash.csv coinmetrics DASHUSD
python dataset.py load temp-uploads ohlcv/doge.csv ohlcv DOGEUSD
python dataset.py load temp-uploads coinmetrics/doge.csv coinmetrics DOGEUSD
python dataset.py load temp-uploads ohlcv/eos.csv ohlcv EOSUSD
python dataset.py load temp-uploads coinmetrics/eos.csv coinmetrics EOSUSD
python dataset.py load temp-uploads ohlcv/etc.csv ohlcv ETCUSD
python dataset.py load temp-uploads coinmetrics/etc.csv coinmetrics ETCUSD
python dataset.py load temp-uploads ohlcv/eth.csv ohlcv ETHUSD
python dataset.py load temp-uploads coinmetrics/eth.csv coinmetrics ETHUSD
python dataset.py load temp-uploads ohlcv/link.csv ohlcv LINKUSD
python dataset.py load temp-uploads coinmetrics/link.csv coinmetrics LINKUSD
python dataset.py load temp-uploads ohlcv/ltc.csv ohlcv LTCUSD
python dataset.py load temp-uploads coinmetrics/ltc.csv coinmetrics LTCUSD
python dataset.py load temp-uploads ohlcv/neo.csv ohlcv NEOUSD
python dataset.py load temp-uploads coinmetrics/neo.csv coinmetrics NEOUSD
python dataset.py load temp-uploads ohlcv/qtum.csv ohlcv QTUMUSD
python dataset.py load temp-uploads coinmetrics/qtum.csv coinmetrics QTUMUSD
python dataset.py load temp-uploads ohlcv/trx.csv ohlcv TRXUSD
python dataset.py load temp-uploads coinmetrics/trx.csv coinmetrics TRXUSD
python dataset.py load temp-uploads ohlcv/usdt.csv ohlcv USDTUSD
python dataset.py load temp-uploads coinmetrics/usdt.csv coinmetrics USDTUSD
python dataset.py load temp-uploads ohlcv/ven.csv ohlcv VENUSD
python dataset.py load temp-uploads coinmetrics/ven.csv coinmetrics VENUSD
python dataset.py load temp-uploads ohlcv/waves.csv ohlcv WAVESUSD
python dataset.py load temp-uploads coinmetrics/waves.csv coinmetrics WAVESUSD
python dataset.py load temp-uploads ohlcv/xem.csv ohlcv XEMUSD
python dataset.py load temp-uploads coinmetrics/xem.csv coinmetrics XEMUSD
python dataset.py load temp-uploads ohlcv/xmr.csv ohlcv XMRUSD
python dataset.py load temp-uploads coinmetrics/xmr.csv coinmetrics XMRUSD
python dataset.py load temp-uploads ohlcv/xrp.csv ohlcv XRPUSD
python dataset.py load temp-uploads coinmetrics/xrp.csv coinmetrics XRPUSD
python dataset.py load temp-uploads ohlcv/zec.csv ohlcv ZECUSD
python dataset.py load temp-uploads coinmetrics/zec.csv coinmetrics ZECUSD
python dataset.py load temp-uploads ohlcv/zrx.csv ohlcv ZRXUSD
python dataset.py load temp-uploads coinmetrics/zrx.csv coinmetrics ZRXUSD