@echo off
python manage_dataset.py load temp-uploads coinmetrics_new/ada.csv coinmetrics_new ADAUSD
python manage_dataset.py load temp-uploads coinmetrics_new/bch.csv coinmetrics_new BCHUSD
python manage_dataset.py load temp-uploads coinmetrics_new/bnb.csv coinmetrics_new BNBUSD
python manage_dataset.py load temp-uploads coinmetrics_new/btc.csv coinmetrics_new BTCUSD
python manage_dataset.py load temp-uploads coinmetrics_new/btg.csv coinmetrics_new BTGUSD
python manage_dataset.py load temp-uploads coinmetrics_new/dash.csv coinmetrics_new DASHUSD
python manage_dataset.py load temp-uploads coinmetrics_new/doge.csv coinmetrics_new DOGEUSD
python manage_dataset.py load temp-uploads coinmetrics_new/eos.csv coinmetrics_new EOSUSD
python manage_dataset.py load temp-uploads coinmetrics_new/etc.csv coinmetrics_new ETCUSD
python manage_dataset.py load temp-uploads coinmetrics_new/eth.csv coinmetrics_new ETHUSD
python manage_dataset.py load temp-uploads coinmetrics_new/link.csv coinmetrics_new LINKUSD
python manage_dataset.py load temp-uploads coinmetrics_new/ltc.csv coinmetrics_new LTCUSD
python manage_dataset.py load temp-uploads coinmetrics_new/neo.csv coinmetrics_new NEOUSD
python manage_dataset.py load temp-uploads coinmetrics_new/qtum.csv coinmetrics_new QTUMUSD
python manage_dataset.py load temp-uploads coinmetrics_new/trx.csv coinmetrics_new TRXUSD
python manage_dataset.py load temp-uploads coinmetrics_new/usdt.csv coinmetrics_new USDTUSD
python manage_dataset.py load temp-uploads coinmetrics_new/ven.csv coinmetrics_new VENUSD
python manage_dataset.py load temp-uploads coinmetrics_new/waves.csv coinmetrics_new WAVESUSD
python manage_dataset.py load temp-uploads coinmetrics_new/xem.csv coinmetrics_new XEMUSD
python manage_dataset.py load temp-uploads coinmetrics_new/xmr.csv coinmetrics_new XMRUSD
python manage_dataset.py load temp-uploads coinmetrics_new/xrp.csv coinmetrics_new XRPUSD
python manage_dataset.py load temp-uploads coinmetrics_new/zec.csv coinmetrics_new ZECUSD
python manage_dataset.py load temp-uploads coinmetrics_new/zrx.csv coinmetrics_new ZRXUSD