@echo off
call plot_trades.cmd ADAUSD
call plot_trades.cmd BCHUSD
call plot_trades.cmd BNBUSD
call plot_trades.cmd BTCUSD
call plot_trades.cmd BTGUSD
call plot_trades.cmd DASHUSD
call plot_trades.cmd DOGEUSD
call plot_trades.cmd EOSUSD
call plot_trades.cmd ETCUSD
call plot_trades.cmd ETHUSD
call plot_trades.cmd LINKUSD
call plot_trades.cmd LTCUSD
call plot_trades.cmd NEOUSD
call plot_trades.cmd QTUMUSD
call plot_trades.cmd TRXUSD
call plot_trades.cmd VENUSD
call plot_trades.cmd WAVESUSD
call plot_trades.cmd XEMUSD
call plot_trades.cmd XMRUSD
call plot_trades.cmd XRPUSD
call plot_trades.cmd ZECUSD
call plot_trades.cmd ZRXUSD